dataset_path: json
test_split: train
output_type: generate_until

doc_to_target: !function utils.doc_to_target

generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false

process_results: !function utils.process_results

metric_list:
  - metric: call_acc
    aggregation: !function utils.aggregate_call_acc
    higher_is_better: true
  - metric: exec_acc
    aggregation: !function utils.aggregate_exec_acc
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  - version: 0.1
  - paper_url: "https://arxiv.org/abs/2502.14752"
  - upstream_repo: "https://github.com/thunlp/TritonBench"
